markdown: rdiscount
highlighter: pygments
fullurl: 'http://okfn.de'
staticurl: /static/
exclude:
  - "CNAME"
  - "Gemfile*"
  - "Readme.md"
  - "scripts/"

gems:
  - jekyll-redirect-from
  - jekyll-sitemap


permalink: blog/:year/:month/:title/
paginate: 8
paginate_path: blog/page/:num/
languages: ["de", "en"]
exclude_from_localizations: ["static", "files", "style", "js", "fonts", "images"]
sass:
    sass_dir: static/style/_scss
    style: compressed
