markdown: rdiscount
highlighter: pygments
fullurl: 'https://okfn.de'
staticurl: /static/
exclude:
  - "CNAME"
  - "Gemfile*"
  - "Readme.md"
  - ".idea/"
  - ".git/"
  - "scripts/"
  - "_site/"
  - "vendor/"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - octopress-autoprefixer
tag_dir: blog/tags/
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
collections:
  projects:
    output: true
    permalink: /projekte/:path/
permalink: blog/:year/:month/:title/
paginate: 8
paginate_path: blog/page/:num/
languages: ["de", "en"]
exclude_from_localizations: ["static", "files", "style", "js", "fonts", "images"]
sass:
  sass_dir: static/style/_scss
  style: compressed
