markdown: rdiscount
highlighter: pygments
baseurl: /
fullurl: 'http://okfn.de'
staticurl: /static/
exclude:
  - "CNAME"
  - "Gemfile*"
  - "Readme.md"
  - "scripts/"

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

collections:
  projects:
    output: true
    permalink: /projekte/:path/


permalink: blog/:year/:month/:title/
paginate: 8
paginate_path: blog/page/:num/

sass:
    sass_dir: static/style/_scss
    style: compressed
